POST localhost:8080/?__GCP_CloudEventsMode=GCS_NOTIFICATION
Content-Type: application/cloudevents+json

{
  "specversion": "1.0",
  "id": "7718729690826582",
  "source": "//storage.googleapis.com/projects/_/buckets/xchange-23",
  "type": "google.cloud.storage.object.v1.finalized",
  "datacontenttype": "application/json",
  "subject": "objects/orders_to_ingest-2023_05_16-19_09_21-282726.zip",
  "time": "2023-05-16T17:09:35.315797Z",
  "bucket": "xchange-23",
  "data": {
    "kind": "storage#object",
    "id": "xchange-23/orders_to_ingest-2023_05_16-19_09_21-282726.zip/1684256975277223",
    "selfLink": "https://www.googleapis.com/storage/v1/b/xchange-23/o/orders_to_ingest-2023_05_16-19_09_21-282726.zip",
    "name": "orders_to_ingest-2023_05_16-19_09_21-282726.zip",
    "bucket": "xchange-23",
    "generation": "1684256975277223",
    "metageneration": "1",
    "contentType": "application/octet-stream",
    "timeCreated": "2023-05-16T17:09:35.315Z",
    "updated": "2023-05-16T17:09:35.315Z",
    "storageClass": "STANDARD",
    "timeStorageClassUpdated": "2023-05-16T17:09:35.315Z",
    "size": "647167",
    "md5Hash": "Gr/7UMe3BmkliIzIwlUB7Q==",
    "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/xchange-23/o/orders_to_ingest-2023_05_16-19_09_21-282726.zip?generation=1684256975277223&alt=media",
    "crc32c": "MqZNtg==",
    "etag": "CKeZ45Wq+v4CEAE="
  }
}
###
